targets:
  gen-db:
    program: sqlc
    args:
      - generate
    cwd: app
  gen-templates:
    program: templ
    args:
      - generate
    cwd: app
  dev-app:
    program: go
    args:
      - run
      - .
    cwd: app
    env_file: .env
    before_hooks:
      - gen-templates
  dev-app-vite:
    program: pnpm
    args:
      - run
      - dev
    cwd: app
  dev-app-health-check:
    program: go
    args:
      - run
      - .
      - health-check
    cwd: app
    env_file: .env
