#!/usr/bin/env bash
#
# Hastily Paste It - The offical Hasty Paste simple CLI
#

# base url, with trailing slash
base_url=${HASTY_PASTE_BASE_URL--}

usage() {
    echo "Hastily Paste It"
    echo "  The offical Hasty Paste simple CLI"
    echo
    echo "Usage: ${0} [OPTION]... <file path>"
    echo
    echo "Options:"
    echo "  -h, --help  Show this message"
    echo
    echo "Environment Variables:"
    echo "  HASTY_PASTE_BASE_URL  base url of server, with a trailing slash"
}

arg1=${1-.}

if [ $arg1 == "." ]
then
    usage
    echo
    echo "ERROR: no arguments given."
    exit 1
elif [ $base_url == "-" ]
then
    usage
    echo
    echo "ERROR: 'HASTY_PASTE_BASE_URL' not set."
    exit 1
elif [ $arg1 == "-h" ] || [ $arg1 == "--help" ]
then
    usage
elif [ -f $arg1 ]
then
    output=$(curl -sS -X POST --data-binary @${arg1} ${base_url}/api/pastes/simple) || exit $?
    echo "${base_url}${output}"
else
    echo "'${arg1}' does not exist"
fi
