baseURL = "https://hastypaste.docs.enchantedcode.co.uk/"
languageCode = "en"
title = "Hasty Paste II"
copyright = "Leo Spratt"

[markup.highlight]
noClasses = false

enableGitInfo = true

[menu]
[[menu.main]]
name = "Home"
url = "/"
[[menu.main]]
name = "Docs"
url = "/docs/"
[[menu.main]]
name = "About"
url = "/about/"
[[menu.sub]]
name = "Repository"
url = "https://github.com/enchant97/hasty-paste"
[[menu.sub.params]]
icon = "git-branch"
hideName = true
[[menu.sub]]
name = "Support The Project"
url = "https://www.buymeacoffee.com/leospratt"
[[menu.sub.params]]
icon = "coffee"

[[params.favicon]]
href = "/icon.svg"

[module]
[[module.imports]]
path = "github.com/enchant97/hugo-mysti-guides"
